### PR TITLE
style/new-design

### LINKED ISSUE #38: Improve design
I am no designer, but I know that the design for the website is terrible and I don;t know how to fix it. I am open to suggestions and design submissions.

### PR DESCRIPTION
**Pull request by thesanjeevsharma**
Hey,

This PR closes #38 

I've improved the UI. It's dark theme based now. 👍  I can do the light theme, but I think it looks much nicer with dark.
It's mobile responsive too. 💯 

#### Suggestion
You can convert time to return 2 digits instead of 1. This way the design will look more consistent.
For example: 0 years should be 00 years

I can create a separate PR for this if you want.

Let me know if any changes are required in this PR.

Thank you

### CODE REVIEW

**Comment by gabLaroche** [comment]
Wow it looks amazing! It's way better than what I could've ever come up with. I do have few notes though
- I agree that it should be double digits, it would be more consistent
- I would appreciate if you didn't reformat all the files (I understand it's probably your editor doing automatically and I know I should set up a prettier/eslint in the project)
- I would like to have an arrow (or more) guiding the user to the countdowns or to have the countdowns above the fold, because it kinda seems like the timers are already over with the "Goodbye, Internet Explorer 11!" and with no indication that the user can scroll to see the timers
- Last little note, since you started after I made some organizational changes in the management of git branches, I would appreciate if you pointed your PR towards the `develop` branch, reason being I want to make fewer larger changes to the production environment.

Other than that, I love the design, the dark mode makes it look really classy, a light/dark toggle could be fun, but really not necessary

**Comment by thesanjeevsharma** [comment]
Thank you for the feedback!

I am really sorry for the formatting. 

Also, should I close this PR and create a new one for `develop`? I'll also implement that change you asked for: indicating the user to scroll.

What do you say?

**Comment by gabLaroche** [comment]
> I am really sorry for the formatting.
No worries! 
> Also, should I close this PR and create a new one for `develop`? I'll also implement that change you asked for: indicating the user to scroll.
>
> What do you say?
Yes I think that would be best!

**Comment by thesanjeevsharma** [comment]
@gabLaroche I've done the changes. 

Good to go! 💯

**Review by gabLaroche — APPROVED** [review]
Looks Great, as mentioned in #38 I will wait until the end of October before merging your PR, just to see if the other assignees come up with good ideas that we can implement in the new design

**Pull request merged**
